### ISSUE TITLE
Error on Build: Could not navigate to '' Reason: Couldn't find route for ''

### ISSUE THREAD

**Issue by muescha** [vaadin/flow-crm-tutorial#10]
i 50% when i run "build application" i get an Error: 

```
Could not navigate to ''
Reason: Couldn't find route for ''
Available routes:
This detailed message is only shown when running in development mode.
```

i solved it with:

```java
@SpringBootApplication(scanBasePackages = {"com.vaadin"})
public class Application extends SpringBootServletInitializer {
```

more possible settings i found here: https://github.com/spring-projects/spring-boot/issues/18109

i think it would be nice to add `scanBasePackages` to the tutorial (and videos, so beginners are not have this error

**Comment by matiasxx** [comment]
Hi there! I'm using Vaadin but without Springboot and i'm having the same issue. Any clue?
